#!/usr/bin/env python

# Pipe command that colors every alternate line
# Creates an effect kind of like an old monitor.

# Dependencies:
#   ansicolors (https://pypi.org/project/ansicolors)

# Author: David McClosky
# Homepage: http://zorglish.org
# Code: http://github.com/dmcc

import fileinput
import colors

lines = iter(fileinput.input())
color = True
for line in lines:
    line = line.rstrip()
    if color:
        print(colors.color(line, fg='green'))
    else:
        print(line)

    color = not color
