#!/usr/bin/env python

# Pipe command that colors every alternate line

# Author: David McClosky
# Homepage: http://zorglish.org
# Code: http://github.com/dmcc
import fileinput, ansi

lines = iter(fileinput.input())
color = True
for line in lines:
    line = line.rstrip()
    if color:
        print(ansi.GREEN + line + ansi.RESET)
    else:
        print(line)

    color = not color
