#!/usr/bin/env python
"""Usage: findwords word1 word2 ... wordN < sometext
Like grep, but prints out lines that contain all words.
See also quickcolorize which is similar but doesn't do filtering."""

# Dependencies:
# needs my waterworks library:
#   https://github.com/dmcc/waterworks

# Author: David McClosky
# Homepage: http://zorglish.org
# Code: http://github.com/dmcc

import sys
import ansi
from QuickColorize import colorize

words = sys.argv[1:]
for line in sys.stdin:
    skip = False
    for word in words:
        if word not in line:
            skip = True
            break
    if not skip:
        for word in words:
            color_word = colorize(word)
            # no ansi.RESET needed since colorize() does that for us
            line = line.replace(word, ansi.BOLD + color_word)
        sys.stdout.write(line)
