#!/usr/bin/env python
"""Usage: findwords word1 word2 ... wordN < sometext
Like grep, but prints out lines that contain all words.
See also quickcolorize which is similar but doesn't do filtering."""

# Dependencies:
# needs my waterworks library:
#   https://bitbucket.org/dmcc/waterworks

# Author: David McClosky
# Homepage: http://zorglish.org
# Code: http://code.zorglish.org

import sys, itertools
import ansi
from QuickColorize import colorize

ansi_colors = [getattr(ansi, attr) for attr in dir(ansi) 
    if attr == attr.upper() and attr not in ('BOLD', 'REVERSE', 'RESET')]
ansi_colors = itertools.cycle(ansi_colors)

words = sys.argv[1:]
for line in sys.stdin:
    skip = False
    for word in words:
        if word not in line:
            skip = True
            break
    if not skip:
        for word in words:
            color_word = colorize(word)
            line = line.replace(word, ansi.BOLD + color_word) # no ansi.RESET needed since colorize() does that for us
        sys.stdout.write(line)
