#!/usr/bin/env python

# Print out the full path to a filename and copy it to the X clipboard.
# If multiple filenames are given, only the last one will be copied to
# the clipboard. Requires 'xclip' for clipboard copying but will still
# work without it.

# If your filesystem is filled with ugly symlinks, you can write
# a function called cleanup_path in the localsite.paths module.
# The function should take one string parameter with an absolute path
# and return a string. If this function can't be found, no cleanups will
# be performed. Example function:
#   def cleanup_path(filename):
#       if filename.startswith('/old/'):
#           filename = filename[4:]
#       return filename

# Usage: fullpathto [filenames]

# Author: David McClosky
# Homepage: http://zorglish.org
# Code: http://github.com/dmcc

import sys
import os
from path import path

try:
    from localsite.paths import cleanup_path
except ImportError:
    cleanup_path = lambda filename: filename

args = sys.argv[1:] or ['.']
for filename in args:
    fullpath = path(cleanup_path(path(filename).abspath()))
    print fullpath
    if not fullpath.exists():
        print '\twarning: above path does not exist'
    command = "echo '%s' | xclip -in" % fullpath
    os.system(command)
