#!/usr/bin/env python

# simple way to graph numbers in a text file
# example usage: graphex "F1 score for threshold (\S+) is (\S+)\(P (\S+), R (\S+)\)"
#                                                X        Y1       Y2       Y3
# will make a scatter plot of X vs Y1, X vs Y2, and X vs Y3

# Author: David McClosky
# Homepage: http://zorglish.org
# Code: http://code.zorglish.org

import sys, re, pylab
regex = re.compile(sys.argv[1])
points = []
for line in sys.stdin:
    match = regex.search(line)
    if match:
        points.append(map(float, match.groups()))

colors = iter('brg')

transformed = zip(*points)
x = transformed[0]
for y in transformed[1:]:
    pylab.scatter(x, y, c=colors.next())
pylab.show()
