#!/usr/bin/env python
import sys, os
from path import path

# Run Java from a file instead of a Java class.  This is intended to let you use standard shell completion instead of typing long Java class names.
# This assumes that $CLASSPATH is set.

# Requires path.py from https://github.com/dmcc/path.py or similar.

# Author: David McClosky
# Homepage: http://zorglish.org
# Code: http://code.zorglish.org

java = os.getenv('JAVA', 'java') # let people override the Java binary with $JAVA

args = sys.argv[1:]
jvm_args = []
while 1:
    top = args[0]
    if top.startswith('-'):
        jvm_args.append(args.pop(0))
    else:
        break

filename = path(args.pop(0))
if not filename.exists():
    raise SystemExit("File %s doesn't exist." % filename)

package = None
for line in file(filename):
    line = line.strip()
    if line.startswith('package') and line.endswith(';'):
        # e.g. "package edu.stanford.nlp.annotation;"
        package = line.split()[1][:-1]
        break

if not package:
    raise SystemExit("Couldn't find Java package in %s" % filename)

classname = package + '.' + filename.basename().stripext()
command = ' '.join([java] + jvm_args + [classname] + args)
print >>sys.stderr, '%s: running %r' % (sys.argv[0], command)
os.system(command)
