#!/usr/bin/env python
"""Join k lines together with a space character.
Usage:
    shell> cat inputfile
    line1
    line2
    line3
    line4
    [...]

    shell> joink 2 < inputfile
    line1 line2
    line3 line4
    [...]
"""

# Dependencies:
# needs my waterworks library:
#   https://github.com/dmcc/waterworks

# Author: David McClosky
# Homepage: http://zorglish.org
# Code: http://github.com/dmcc

from iterextras import batch
import argparse
import fileinput
import sys

parser = argparse.ArgumentParser()
parser.add_argument(
    "filenames", metavar="F", type=str, nargs="*", help="Filenames to read from"
)
parser.add_argument("-s", "--separator", help="", default=" ")
parser.add_argument(
    "-n", "--num-lines", help="How many lines to join", type=int, default=2
)
args = parser.parse_args()

for lines in batch(fileinput.input(files=args.filenames), batchsize=args.num_lines):
    lines = [line.rstrip() for line in lines]
    print(args.separator.join(lines))
