#!/usr/bin/env python
"""Join k lines together with a space character.
Usage:
    shell> cat inputfile
    line1
    line2
    line3
    line4
    [...]

    shell> joink 2 < inputfile
    line1 line2
    line3 line4
    [...]
"""

# Dependencies:
# needs my waterworks library:
#   https://bitbucket.org/dmcc/waterworks

# Author: David McClosky
# Homepage: http://zorglish.org
# Code: http://github.com/dmcc

# TODO: configurable separator

import sys
from iterextras import batch

k = int(sys.argv[-1])
separator = ' '
for lines in batch(sys.stdin, batchsize=k):
    lines = [line.rstrip() for line in lines]
    print(separator.join(lines))
