#!/usr/bin/env python
import fileinput
import re
from waterworks.Strings import multisplit

# Author: David McClosky
# Homepage: http://zorglish.org
# Code: http://code.zorglish.org

depth = 0
sentence_count = 0
for line in fileinput.input():
    for token in re.split(r'([\(\)])', line):
        token = token.strip()
        if not token:
            continue
        if depth == 0:
            print "--- Sentence %d --- " % sentence_count
            sentence_count += 1
        if token == '(':
            print "%s%s" % ('. ' * depth, token)
            depth += 1
        elif token == ')':
            depth -= 1
            print "%s%s" % ('. ' * depth, token)
            if depth < 0:
                raise ValueError("Too many )s")
        else:
            print "%s%s" % ('. ' * depth, token)

if depth != 0:
    raise ValueError("Not enough )s -- depth wasn't 0 at end.")
