#!/usr/bin/env python
import fileinput
import re

# Author: David McClosky
# Homepage: http://zorglish.org
# Code: http://github.com/dmcc

depth = 0
sentence_count = 0
for line in fileinput.input():
    for token in re.split(r'([\(\)])', line):
        token = token.strip()
        if not token:
            continue
        if depth == 0:
            print("--- Sentence %d --- " % sentence_count)
            sentence_count += 1
        if token == '(':
            print("{}{}".format('. ' * depth, token))
            depth += 1
        elif token == ')':
            depth -= 1
            print("{}{}".format('. ' * depth, token))
            if depth < 0:
                raise ValueError("Too many )s")
        else:
            print("{}{}".format('. ' * depth, token))

if depth != 0:
    raise ValueError("Not enough )s -- depth wasn't 0 at end.")
