#!/usr/bin/env python
# vi: syntax=python
# visualize the diff between two bits of text:
#   paste in first bit of text
#   hit Control-D
#   paste in second bit of text
#   see result in vimdiff

# Dependencies:
# needs my waterworks library:
#   https://bitbucket.org/dmcc/waterworks

# Author: David McClosky
# Homepage: http://zorglish.org
# Code: http://code.zorglish.org

import sys
from vimdiff import vimdiff

# TODO could be generalized to K bits of text

text1 = sys.stdin.read().strip()
print "Read text 1 (%s chars)" % len(text1)
text2 = sys.stdin.read().strip()
print "Read text 2 (%s chars)" % len(text2)

vimdiff(text1, text2)
