#!/usr/bin/env python

# essentially my alarm clock logic -- handles any date/time format that mx.DateTime can handle

# Dependencies:
#   mx.DateTime: http://pypi.python.org/pypi/egenix-mx-base/

# Author: David McClosky
# Homepage: http://zorglish.org
# Code: http://github.com/dmcc

import mx.DateTime, sys, time

wakeuptime = mx.DateTime.Parser.DateTimeFromString("".join(sys.argv[1:]))
diff = wakeuptime - mx.DateTime.now()

if diff.seconds > 0:
    print "Sleeping until:", wakeuptime, "(%s)" % diff
    time.sleep(diff.seconds)
else:
    sys.exit(1)
