#!/usr/bin/env python

# essentially my alarm clock logic -- handles any date/time format that
# dateparser can handle

# Dependencies:
#   dateparser

# Author: David McClosky
# Homepage: http://zorglish.org
# Code: http://github.com/dmcc

import dateparser, datetime, sys, time

wakeuptime = dateparser.parse("".join(sys.argv[1:]))
diff = wakeuptime - datetime.datetime.now()

if diff.total_seconds() > 0:
    print("Sleeping until:", wakeuptime, "(%s)" % diff)
    time.sleep(diff.total_seconds())
else:
    sys.exit(1)
