#!/usr/bin/env python

"""
Pipe command that sorts the characters in each line:
    shell> echo "by ill ow" | sortchars
      billowy
"""

# Author: David McClosky
# Homepage: http://zorglish.org
# Code: http://github.com/dmcc

import fileinput
for line in fileinput.input():
    line = line.rstrip()
    print(''.join(sorted(line)))
