#!/usr/bin/env python

"""
Pipe command that sorts each line by its length (ascending).
"""

# Author: David McClosky
# Homepage: http://zorglish.org
# Code: http://github.com/dmcc

# TODO: add option for reverse sort

import fileinput
lines = list(fileinput.input())

def by_length(line):
    return (len(line), line)

for line in sorted(lines, key=by_length):
    print(line[:-1])
