#!/usr/bin/env python

"""
Find a number in each line and sort all lines by that, descending.
"""

# Author: David McClosky
# Homepage: http://zorglish.org
# Code: http://github.com/dmcc

import fileinput
import re

NUM_RE = re.compile(r'(\d+\.?\d*)')

num_and_line_pairs = []

for line in fileinput.input():
    if not line.strip():
        continue

    num = float(NUM_RE.search(line).group(1))
    # Negative so we sort descendingly.
    num_and_line_pairs.append((-num, line))

print(''.join([line
      for num, line in sorted(num_and_line_pairs)]))
