#!/usr/bin/env python

# a quick command-line program for adding up a list of numbers
# white space is ignored

# Author: David McClosky
# Homepage: http://zorglish.org
# Code: http://github.com/dmcc

import sys
from waterworks.Strings import sumstring

text = ' '.join(sys.argv[1:])
if not text:
    text = sys.stdin.read()

print('Sum:', sumstring(text))
