#!/usr/bin/env python

# put "thrash" before your command and the command will be monitored
# for thrashing

# Dependencies:
#   ansicolors (https://pypi.org/project/ansicolors)

# Author: David McClosky
# Homepage: http://zorglish.org
# Code: http://github.com/dmcc

import os
import sys
import time

import colors

period = int(os.getenv('THRASH_PERIOD', '15'))

command = sys.argv[1:]
print("Command:", ' '.join(command))

pid = os.fork()
if pid == 0: # child
    os.execvp(command[0], command)
else: # parent
    maxes = {}
    while 1:
        print()
        print(colors.color(f"[Time: {time.asctime()}", fg='red'), end=' ')
        stats = []
        for line in open('/proc/%s/status' % pid):
            if line.startswith('Vm'):
                # example line: "VmRSS:      1036 kB"
                attr, val, unit = line.split()
                attr = attr[:-1]
                val = int(val)
                stats.append(f"{attr}: {val}")
                maxes.setdefault(attr, 0)
                maxes[attr] = max(maxes[attr], val)
        if stats:
            print(colors.color("Cur: " + ", ".join(stats), fg='red'))
        else:
            raise SystemExit # XXX bad hack
        print(colors.color("Max " + ', '.join(["%s: %s" % pair
                        for pair in maxes.items()]) + "]", fg='red'))
        time.sleep(period)
