#!/usr/bin/env python

# Lets you launch vi and jump to a specific line using colons
# (commonly found in stack traces, etc.)
# e.g., 'viline file1:7' will start you out on line 7 of file1
# set $VISUAL to point to your vim binary (e.g. gvim, vimx, etc.)

# Author: David McClosky
# Homepage: http://zorglish.org
# Code: http://github.com/dmcc

import os
import sys
import subprocess

editor = os.getenv('VISUAL', 'gvim')

def split(arg):
    if ':' in arg:
        pieces = arg.split(':', 1)
        return [pieces[0], '+' + pieces[1]]
    else:
        return [arg]

args = map(split, sys.argv[1:])
command = list(*args)
command.insert(0, editor)
subprocess.call(command)
